version: '3'

services: 
    app:
        build: .
        container_name: nestjs-maratona-lives
        entrypoint: ./.docker/entrypoint.sh
        ports: 
            - 3000:3000
        volumes: 
            - .:/home/node/app
